# Generated by Django 4.1.2 on 2022-10-25 06:35

import django.core.validators
from django.db import migrations, models
import exam_feb_2022.my_music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), exam_feb_2022.my_music.models.letters_numbers_val], verbose_name='Username')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
