# Generated by Django 4.1.2 on 2022-10-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_music', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.URLField(verbose_name='Image URL'),
        ),
    ]
