# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Library CI/CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      name: Use Node.js ${{ matrix.node-version }}

    - uses: actions/setup-node@v3
      name: Use Node.js 18.x
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install
      name: Install dependencies

    - run: npm i -g pm2
      name: Install pm 2
   
    - run: pm2 start server/server.js
      name: Start API server
   
    - name: Install playwright browsers
      run: npx playwright install --with-deps
   
    - name: Run tests
      run: npx playwright test
   
    - name: Stop server
      run: pm2 stop server

  deploy:
    name: "Deploy on Reneder.com"
    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Render Deploy Action
    # You may pin to the exact commit or the version.
    # uses: johnbeynon/render-deploy-action@a0588f9aca995a15d69a72cb2bfbf37c12e5b540
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        # ID of the service to deploy
        service-id: ${{ secrets.LIBRARY_SERVICE_ID }}
        # A Render API key
        api-key: ${{ secrets.LIBRARY_RENDER_API }}
