# Generated by Django 4.1.1 on 2022-10-05 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_alter_employee_projects_accesscard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscard',
            name='id',
        ),
        migrations.AlterField(
            model_name='accesscard',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='web.employee'),
        ),
    ]
