# Generated by Django 4.1.3 on 2022-11-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_appuser_managers_appuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='date_joined',
        ),
    ]
