apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-client-to-consumer
  namespace: projectx
spec:
  podSelector:
    matchLabels:
      app: client
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: consumer
