apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: projectx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: shekeriev/k8s-oracle
        ports:
        - containerPort: 82
