apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devguru-binding
  namespace: projectx
subjects:
- kind: User
  name: ivan
- kind: User
  name: mariana
roleRef:
  kind: Role
  name: devguru
  apiGroup: rbac.authorization.k8s.io