apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gurus-clusterrolebinding
subjects:
- kind: User
  name: ivan
- kind: User
  name: mariana
roleRef:
  kind: ClusterRole
  name: gurus-clusterrole
  apiGroup: rbac.authorization.k8s.io
