apiVersion: v1
kind: LimitRange
metadata:
  name: projectx-limitrange
  namespace: projectx
spec:
  limits:
  - type: Container
    default:
      memory: 256Mi
      cpu: 100m
    defaultRequest:
      memory: 128Mi
      cpu: 50m
    max:
      memory: 512Mi
      cpu: 500m
    min:
      memory: 64Mi
      cpu: 10m
