apiVersion: v1
kind: Pod
metadata:
  name: pod-init
  labels:
    app: pod-init
spec:
  containers:
  - name: cont-main
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: cont-init-1
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
      - echo "$(date +'%d-%m-%Y %H:%M:%S') => begin initialization ..." >> /data/index.html;
        sleep 10;
        echo "$(date +'%d-%m-%Y %H:%M:%S') => ... done" >> /data/index.html;
    volumeMounts:
    - name: data
      mountPath: /data
  - name: cont-init-2
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
      - echo "$(date +'%d-%m-%Y %H:%M:%S') => launching the application ..." >> /data/index.html;
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: svc-init
  labels:
    app: svc-init
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: pod-init
